name: Build Minified Version

on:
  push:
    branches: [ main, master ]
    paths:
      - 'index.js'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'index.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build minified version
      run: bun run build

    - name: Check file sizes
      run: |
        echo "📊 Build Results:"
        echo "Original: $(ls -lh index.js | awk '{print $5}')"
        echo "Minified: $(ls -lh index.min.js | awk '{print $5}')"

    - name: Commit minified file
      if: github.event_name == 'push'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.min.js
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-build: Update index.min.js"

    - name: Push changes
      if: github.event_name == 'push'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}